### ISSUE TITLE
I like the idea but lack the knowledge, can you please give me some references to study?

### ISSUE THREAD

**Issue by get-thepacket** [pranjulps3/pluto#2]

**Comment by pranjulps3** [comment]
@get-thepacket I have created a wiki on the tentative technical architecture of discovery. I am also new to streaming data across devices in a network so take I am doing my research. I will post references as I go forward on a different wiki so keep an eye over it. You can be a contributor if you're interested.

**Comment by get-thepacket** [comment]
@pranjulps3 I am really new in this development field, I have only done a bit of node.js and worked on a small express project. I am looking forward to contribute.
